<a href="https://colab.research.google.com/github/jdavilasoft/DSRP-Taller-Virtual-python/blob/main/DSRP_Taller_Virtual_Python_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Creando listas
# No importa el tipo de datos
lista1 = [10, 20, 30]
print(lista1)

lista2 = ['homero', 'marge', 'bart']
print(lista2)

lista3 = ['pepito', 50, 69]
print(lista3)

[10, 20, 30]
['homero', 'marge', 'bart']
['pepito', 50, 69]


In [ ]:
# Ejemplo
nombres = ['jose', 'martin', 'salvador']
edad = [43, 56, 49]
universidad = ['ucsm', 'uni', 'pucp']

# Acceder a elementos
print(nombres[1])
print(universidad[2])

# Longitud de a lista
print("Numero de estudiantes:", len(nombres))

martin
pucp
Numero de estudiantes: 3


In [ ]:
# Recorrer una lista
for item in nombres:
  print(item)

jose
martin
salvador


In [ ]:
# Otro ejemplo para recorrer una lista
for i in range(len(nombres)):
  print(nombres[i].capitalize(), 'tiene', edad[i], 'anios, y estudia en', universidad[i].upper())

Jose tiene 43 anios, y estudia en UCSM
Martin tiene 56 anios, y estudia en UNI
Salvador tiene 49 anios, y estudia en PUCP
Javier tiene 35 anios, y estudia en DE LA VIDA


In [ ]:
# Agregar elementos a una lista
nombres.append('javier')
edad.append(35)
universidad.append('de la vida')

In [ ]:
# Saber el indica de un elemento
print(nombres.index('javier'))
print(edad.index(56))
print(universidad.index('ucsm'))

3
1
0


In [ ]:
# Ejemplo
alumno = ['alice', 'bob', 'claudio', 'dionisio', 'erica', 'fiorella', 'gregorio']
nota = [19, 18, 10, 14, 14, 20, 10]

for i in range(len(alumno)):
  if (nota[i] > 10):
    print(alumno[i].capitalize(), 'aprobado')
  else:
    print(alumno[i].capitalize(), 'desaprobado')

Alice aprobado
Bob aprobado
Claudio desaprobado
Dionisio aprobado
Erica aprobado
Fiorella aprobado
Gregorio desaprobado


In [ ]:
# Otro ejemplo
nombres = ['luis', 'roberto', 'silvia', 'francisco', 'josefina']
apellidos = ['rivas', 'peralta', 'monteza', 'contreras', 'perez']
edad = [30, 15, 21, 12, 30]

for i in range(len(nombres)):
  if edad[i] >= 18:
    print(nombres[i].capitalize(), apellidos[i].capitalize(), 'es mayor de edad')
  else:
    print(nombres[i].capitalize(), apellidos[i].capitalize(), 'es menor de edad')

Luis Rivas es mayor de edad
Roberto Peralta es menor de edad
Silvia Monteza es mayor de edad
Francisco Contreras es menor de edad
Josefina Perez es mayor de edad


In [ ]:
# LIBRERIA NUMPY
import numpy as np
v = np.array([1,2,3])
print(v)

s = np.array([3,4,5])
print(s)

[1 2 3]
[3 4 5]


In [ ]:
# Operaciones
print(v + s)
print(v - s)
print(v * s)

[4 6 8]
[-2 -2 -2]
[ 3  8 15]


In [ ]:
# Producto escalar 1*3 + 2*4 + 3*5
pe = v.dot(s)
print('El producto escalar de v*s es:', pe)

El producto escalar de v*s es: 26


In [ ]:
# Acceder a elementos (igual al acceso que las listas)
print(v[0])
print(s[1])

1
4


In [ ]:
# Matrices
a = np.array([[1, 9, 10], [7, 12, 21], [9, 7, 1]])
print('Esta es la matriz a:\n', a)

print('')

b = np.array([[3,4,34], [5,6,2], [1,2,3]])
print('Esta es la matriz b:\n', b)

Esta es la matriz a:
 [[ 1  9 10]
 [ 7 12 21]
 [ 9  7  1]]

Esta es la matriz b:
 [[ 3  4 34]
 [ 5  6  2]
 [ 1  2  3]]


In [ ]:
# Acceder a elementos de la matriz
print('Elementos de la matriz A')
print('Primer elemento:', a[0][0])
print('Elemento central:', a[1][1])
print('Ultimo elemento:', a[2][2])

print('')

print('Elementos de la matriz B')
print('Primer elemento:', b[0][0])
print('Elemento central:', b[1][1])
print('Ultimo elemento:', b[2][2])

Elementos de la matriz A
Primer elemento: 1
Elemento central: 12
Ultimo elemento: 1

Elementos de la matriz B
Primer elemento: 3
Elemento central: 6
Ultimo elemento: 3


In [ ]:
# Acceder a una fila
print('Segunda fila de la matriz A:', a[1])
print('Tercera fila de la matriz B:', b[2])

print('')

# Acceder a una columna
print('Segunda fila de la matriz A:', a[:,1])
print('Tercera fila de la matriz B:', b[:,2])

Segunda fila de la matriz A: [ 7 12 21]
Tercera fila de la matriz B: [1 2 3]

Segunda fila de la matriz A: [ 9 12  7]
Tercera fila de la matriz B: [34  2  3]


In [ ]:
# Operaciones con matrices
# Deben tener el mismo numero de filas y columnas

print('La suma de matrices:\n', a + b)
print('')
print('El producto de matrices:\n', a * b)


La suma de matrices:
 [[ 4 13 44]
 [12 18 23]
 [10  9  4]]

El producto de matrices:
 [[  3  36 340]
 [ 35  72  42]
 [  9  14   3]]


In [ ]:
# Produto escalar de matrices
x = np.array([[1,2],[3,4]])
print('Matriz X:\n', x, '\n')
y = np.array([[5,6],[7,8]])
print('Matriz Y:\n', y, '\n')
print(np.dot(x, y))
# El calculo es el siguiente
# [1*5 + 2*7, 1*6 + 2*8][3*5 + 4*7, 3*6 + 4*8]

Matriz X:
 [[1 2]
 [3 4]] 

Matriz Y:
 [[5 6]
 [7 8]] 

[[19 22]
 [43 50]]


In [ ]:
# Otro ejemplo con las matrices a y b
print(np.dot(a, b))

[[ 58  78  82]
 [102 142 325]
 [ 63  80 323]]


In [ ]:
# Matriz identidad
print('Esta es una matriz identidad')
z = np.eye(5)
print(z)

Esta es una matriz identidad
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
# Arrays utiles
r = np.arange(-100, 100, 2) # Valor inicia, valor final, incremento (for)
print(r)

[-100  -98  -96  -94  -92  -90  -88  -86  -84  -82  -80  -78  -76  -74
  -72  -70  -68  -66  -64  -62  -60  -58  -56  -54  -52  -50  -48  -46
  -44  -42  -40  -38  -36  -34  -32  -30  -28  -26  -24  -22  -20  -18
  -16  -14  -12  -10   -8   -6   -4   -2    0    2    4    6    8   10
   12   14   16   18   20   22   24   26   28   30   32   34   36   38
   40   42   44   46   48   50   52   54   56   58   60   62   64   66
   68   70   72   74   76   78   80   82   84   86   88   90   92   94
   96   98]


In [ ]:
# Crea un array usando linspace
# Valor inicial, valor final, numero de elementos
t = np.linspace(0, 10, 20)
print(t)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]
